### ISSUE TITLE
[BUG] - Not exporting attachments to confluence

### ISSUE THREAD

**Issue by rui-costa** [simasbu/confluence-site-descriptor-action#20]
## Steps to Reproduce:
1. Create a new page
1. Add attachment files
1. Push changes to master
1. Check in confluence for attachments ( attachment are missing )

## Expected Behaviour
* Files in attachment folder are exported to confluence as attachments

**Comment by simasbu** [comment]
#21

**Comment by barchewbacca** [comment]
The fix by @simasbu is merged to master now, so I am closing the issue.
